apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: my-app
type: Opaque
stringData:
  APP_KEY: base64:mRAZh0bwtePWtZB4dTCnVRAFVcFobb+XMUge3cD5i9U=
  DB_USERNAME: loan_user
  DB_PASSWORD: n9NZ3uYNkbANjyEq